version: "3.9"

services:

  postgres_db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: restaurant
    networks:
      - restaurant_network
    expose:
      - 5432
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant_app
    restart: always
    networks:
      - restaurant_network
    expose:
      - 15400
    ports:
      - "8000:15400"
    volumes:
      - ./app:/app
    depends_on:
      - postgres_db

networks:
  restaurant_network:
    name: restaurant_network