FROM python:3.10-slim

WORKDIR /tests/

COPY requirements.txt .

RUN apt-get update && apt-get install -y libpq-dev build-essential
RUN pip install -r requirements.txt --no-cache-dir

COPY . .

CMD ["pytest", "--tb=long", "."]